services:
  - type: web
    name: openchessclub
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        fromDatabase:
          name: openchessclub-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production

databases:
  - name: openchessclub-db